name: lexyapp
description: "A new Flutter project."

version: 1.3.0+20

environment:
  sdk: ">=3.7.0 <4.0.0"  # This should be fine since Dart 3.2.0 should work with this version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_ui_firestore: ^1.7.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^19.0.0
  cloud_firestore: ^5.4.4
  persistent_bottom_nav_bar: ^6.2.1
  google_fonts: ^6.2.1
  social_auth_btn_kit: ^0.1.3
  intl: any
  phone_form_field: ^10.0.5
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.9.0
  sign_in_with_apple: ^6.1.3
  location: ^8.0.0
  syncfusion_flutter_calendar: ^28.2.12
  flutter_facebook_auth: ^7.1.1
  firebase_phone_auth_handler: ^1.1.0
  pinput: ^5.0.0
  image_picker: ^1.1.2
  flutter_material_pickers: ^3.7.0
  firebase_storage: ^12.3.7
  google_maps_place_picker_mb: ^3.1.2
  flutter_swiper_null_safety: ^1.0.2
  introduction_screen: ^3.1.14
  cloud_functions: ^5.3.0
  calendar_view: ^1.4.0
  url_launcher: ^6.3.1
  excel: ^4.0.6
  add_2_calendar: ^3.0.1
  path_provider: ^2.0.10
  # permission_handler: ^10.2.0
  open_file: ^3.5.10
  go_router: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  package_rename: ^1.7.1
  flutter_launcher_icons: ^0.14.3

package_rename_config:
  android:
    app_name: "LexyApp"
    package_name: "com.techpro.lexyapp"
    override_old_package: true
    lang: kotlin

  ios:
    app_name: "LexyApp"
    bundle_name: "LexyApp"
    package_name: "com.techpro.lexyapp"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "Assets/playstore.png"  # Path to your new icon

flutter:
  uses-material-design: true

  assets:
    - Assets/
