name: lexyapp
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_ui_firestore: ^1.7.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.4
  cloud_firestore: ^5.4.4
  persistent_bottom_nav_bar: ^6.2.1
  google_fonts: ^6.2.1
  social_auth_btn_kit: ^0.1.3
  intl: any
  phone_form_field: ^9.2.8
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.9.0
  sign_in_with_apple: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  package_rename: ^1.7.1
  


package_rename_config:
  android:
    app_name: "LexyApp"                # Display name of the Android app
    package_name: "com.techpro.lexyapp"  # Android package name
    override_old_package: true           # Remove the old package structure if it exists
    lang: kotlin                          # Language of the Android codebase (kotlin/java)

  ios:
    app_name: "LexyApp"                  # Display name of the iOS app
    bundle_name: "LexyApp"               # Display name shown in the iOS settings
    package_name: "com.techpro.lexyapp"  # Product bundle identifier for iOS

flutter:
  uses-material-design: true
